export enum ErrorMessage {
  UPDATE_FAILED = 'Failed to update',
  INSERT_FAILED = 'Failed to insert',
  INFO_NOT_FOUND = 'information not found',
  DELETE_FAILED = 'Failed to delete',
  RECORD_NOT_FOUND = 'No Record found!',
  EMAIL_NOT_FOUND = 'Email not found!',
  FAILED_TO_RESET = 'Failed to reset',
  TOKEN_EXPIRED = 'token expired!',
  FILE_UPLOAD_FAILED = 'Failed to upload file!',
  NO_USER_FOUND = 'NO USER FOUND!',
  NOT_A_VALID_USER = 'NOT A VALID USER!',
  ALREADY_ADDED = 'ALREADY ADDED!',
  SOMETHING_WENT_WRONG = 'Something Went Wrong!',
  STATUS_CHANGE_SUCCESS = 'Status Changed Successfully',
  STATUS_CHANGE_FAILED = 'Failed To Change Status',
  UNAUTHORIZED = 'Unauthorized',
}
