export enum StudentActivityTypesEnum {
  CONVERSATION = 'conversation',
  CHAT = 'chat',
  REVIEW = 'review',
  SHORTLIST_COURSES = 'shortlist_courses',
  SHORTLIST_UNIVERSITY = 'shortlist_university',
  FAVORITE_UNIVERSITY = 'favorite_university',
  FAVORITE_COURSES = 'favorite_course',
  COMPARE_UNIVERSITY = 'compare_university',
  COMPARE_COURSES = 'compare_courses',
  ARTICLE_BOOKMARK = 'article_bookmark',
  ARTICLE_COMMENT = 'article_comment',
  BROCHURE = 'brochure',
  PROSPECTUS = 'prospectus',
  COURSE_GUIDE = 'course_guide',
  PROFILE_EVOLUTION_EDIT = 'profile_evolution_edit',
  REVIEW_AND_LODGEMENT = 'review_lodgement',
  APPLICATION = 'application',
  OFFER_LETTER = 'offer_letter',
  PAYMENT = 'payment',
  VISA_LODGEMENT = 'visa_lodgement',
  JOINED = 'joined',
}
